# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5ae02ff98e93b0e6f09f13edfee3798745b60704b511b8a85b5057997d04d2a1dd1acf678b79bdcfe24733fc3dbc347b1e65b43e81c6dba7e83de018a8b69ec

test:
  secret_key_base: dc90e0ef1bb6fec012c9753bbeb6e9f9eff5e7698d921e9ea77a8a070e72d0098d5ecaf21fcb5e719a73164bb8ad421c42bcdda5a1b38a71280665ff7a5bcc4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
